package com.twistlet.falcon.model.entity;


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * FalconUser generated by hbm2java
 */
@Entity
@Table(name="falcon_user"
    , uniqueConstraints = {@UniqueConstraint(columnNames="phone"), @UniqueConstraint(columnNames="nric"), @UniqueConstraint(columnNames="email")} 
)
public class FalconUser  implements java.io.Serializable {


     private String username;
     private String password;
     private String name;
     private String email;
     private String phone;
     private String nric;
     private Boolean sendSms;
     private Boolean sendEmail;
     private Boolean valid;
     private Set<FalconPatron> falconPatronsForPatron = new HashSet<FalconPatron>(0);
     private Set<FalconPatron> falconPatronsForAdmin = new HashSet<FalconPatron>(0);
     private Set<FalconUserRole> falconUserRoles = new HashSet<FalconUserRole>(0);
     private Set<FalconService> falconServices = new HashSet<FalconService>(0);
     private Set<FalconStaff> falconStaffs = new HashSet<FalconStaff>(0);
     private Set<FalconLocation> falconLocations = new HashSet<FalconLocation>(0);

    public FalconUser() {
    }

	
    public FalconUser(String username, String password, String name, String email, String phone, String nric) {
        this.username = username;
        this.password = password;
        this.name = name;
        this.email = email;
        this.phone = phone;
        this.nric = nric;
    }
    public FalconUser(String username, String password, String name, String email, String phone, String nric, Boolean sendSms, Boolean sendEmail, Boolean valid, Set<FalconPatron> falconPatronsForPatron, Set<FalconPatron> falconPatronsForAdmin, Set<FalconUserRole> falconUserRoles, Set<FalconService> falconServices, Set<FalconStaff> falconStaffs, Set<FalconLocation> falconLocations) {
       this.username = username;
       this.password = password;
       this.name = name;
       this.email = email;
       this.phone = phone;
       this.nric = nric;
       this.sendSms = sendSms;
       this.sendEmail = sendEmail;
       this.valid = valid;
       this.falconPatronsForPatron = falconPatronsForPatron;
       this.falconPatronsForAdmin = falconPatronsForAdmin;
       this.falconUserRoles = falconUserRoles;
       this.falconServices = falconServices;
       this.falconStaffs = falconStaffs;
       this.falconLocations = falconLocations;
    }
   
     @Id 

    
    @Column(name="username", unique=true, nullable=false, length=100)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=64)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="name", nullable=false, length=200)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="email", unique=true, nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="phone", unique=true, nullable=false, length=25)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="nric", unique=true, nullable=false, length=20)
    public String getNric() {
        return this.nric;
    }
    
    public void setNric(String nric) {
        this.nric = nric;
    }

    
    @Column(name="send_sms")
    public Boolean getSendSms() {
        return this.sendSms;
    }
    
    public void setSendSms(Boolean sendSms) {
        this.sendSms = sendSms;
    }

    
    @Column(name="send_email")
    public Boolean getSendEmail() {
        return this.sendEmail;
    }
    
    public void setSendEmail(Boolean sendEmail) {
        this.sendEmail = sendEmail;
    }

    
    @Column(name="valid")
    public Boolean getValid() {
        return this.valid;
    }
    
    public void setValid(Boolean valid) {
        this.valid = valid;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="falconUserByPatron")
    public Set<FalconPatron> getFalconPatronsForPatron() {
        return this.falconPatronsForPatron;
    }
    
    public void setFalconPatronsForPatron(Set<FalconPatron> falconPatronsForPatron) {
        this.falconPatronsForPatron = falconPatronsForPatron;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="falconUserByAdmin")
    public Set<FalconPatron> getFalconPatronsForAdmin() {
        return this.falconPatronsForAdmin;
    }
    
    public void setFalconPatronsForAdmin(Set<FalconPatron> falconPatronsForAdmin) {
        this.falconPatronsForAdmin = falconPatronsForAdmin;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="falconUser")
    public Set<FalconUserRole> getFalconUserRoles() {
        return this.falconUserRoles;
    }
    
    public void setFalconUserRoles(Set<FalconUserRole> falconUserRoles) {
        this.falconUserRoles = falconUserRoles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="falconUser")
    public Set<FalconService> getFalconServices() {
        return this.falconServices;
    }
    
    public void setFalconServices(Set<FalconService> falconServices) {
        this.falconServices = falconServices;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="falconUser")
    public Set<FalconStaff> getFalconStaffs() {
        return this.falconStaffs;
    }
    
    public void setFalconStaffs(Set<FalconStaff> falconStaffs) {
        this.falconStaffs = falconStaffs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="falconUser")
    public Set<FalconLocation> getFalconLocations() {
        return this.falconLocations;
    }
    
    public void setFalconLocations(Set<FalconLocation> falconLocations) {
        this.falconLocations = falconLocations;
    }




}


