package com.twistlet.falcon.model.entity;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FalconAppointment generated by hbm2java
 */
@Entity
@Table(name="falcon_appointment"
)
public class FalconAppointment  implements java.io.Serializable {


     private Integer id;
     private FalconLocation falconLocation;
     private FalconUser falconUser;
     private String service;
     private Date appointmentDate;
     private Date createDate;
     private Date updateDate;
     private String createBy;
     private String updateBy;
     private Set<FalconPatron> falconPatrons = new HashSet<FalconPatron>(0);

    public FalconAppointment() {
    }

	
    public FalconAppointment(FalconUser falconUser) {
        this.falconUser = falconUser;
    }
    public FalconAppointment(FalconLocation falconLocation, FalconUser falconUser, String service, Date appointmentDate, Date createDate, Date updateDate, String createBy, String updateBy, Set<FalconPatron> falconPatrons) {
       this.falconLocation = falconLocation;
       this.falconUser = falconUser;
       this.service = service;
       this.appointmentDate = appointmentDate;
       this.createDate = createDate;
       this.updateDate = updateDate;
       this.createBy = createBy;
       this.updateBy = updateBy;
       this.falconPatrons = falconPatrons;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="location")
    public FalconLocation getFalconLocation() {
        return this.falconLocation;
    }
    
    public void setFalconLocation(FalconLocation falconLocation) {
        this.falconLocation = falconLocation;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="staff", nullable=false)
    public FalconUser getFalconUser() {
        return this.falconUser;
    }
    
    public void setFalconUser(FalconUser falconUser) {
        this.falconUser = falconUser;
    }

    
    @Column(name="service", length=300)
    public String getService() {
        return this.service;
    }
    
    public void setService(String service) {
        this.service = service;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="appointment_date", length=19)
    public Date getAppointmentDate() {
        return this.appointmentDate;
    }
    
    public void setAppointmentDate(Date appointmentDate) {
        this.appointmentDate = appointmentDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="create_by", length=100)
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    
    @Column(name="update_by", length=100)
    public String getUpdateBy() {
        return this.updateBy;
    }
    
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="falconAppointment")
    public Set<FalconPatron> getFalconPatrons() {
        return this.falconPatrons;
    }
    
    public void setFalconPatrons(Set<FalconPatron> falconPatrons) {
        this.falconPatrons = falconPatrons;
    }




}


