package com.twistlet.falcon.model.entity;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FalconPatron generated by hbm2java
 */
@Entity
@Table(name="falcon_patron"
)
public class FalconPatron  implements java.io.Serializable {


     private Integer id;
     private FalconUser falconUserByPatron;
     private FalconUser falconUserByAdmin;

    public FalconPatron() {
    }

    public FalconPatron(FalconUser falconUserByPatron, FalconUser falconUserByAdmin) {
       this.falconUserByPatron = falconUserByPatron;
       this.falconUserByAdmin = falconUserByAdmin;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="patron", nullable=false)
    public FalconUser getFalconUserByPatron() {
        return this.falconUserByPatron;
    }
    
    public void setFalconUserByPatron(FalconUser falconUserByPatron) {
        this.falconUserByPatron = falconUserByPatron;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="admin", nullable=false)
    public FalconUser getFalconUserByAdmin() {
        return this.falconUserByAdmin;
    }
    
    public void setFalconUserByAdmin(FalconUser falconUserByAdmin) {
        this.falconUserByAdmin = falconUserByAdmin;
    }




}


