package com.twistlet.falcon.model.entity;


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FalconUser generated by hbm2java
 */
@Entity
@Table(name="falcon_user"
)
public class FalconUser  implements java.io.Serializable {


     private String username;
     private String password;
     private String name;
     private String email;
     private String phone;
     private Set<FalconPatron> falconPatronsForPatron = new HashSet<FalconPatron>(0);
     private Set<FalconPatron> falconPatronsForAdmin = new HashSet<FalconPatron>(0);
     private Set<FalconAppointmentPatron> falconAppointmentPatrons = new HashSet<FalconAppointmentPatron>(0);
     private Set<FalconUserRole> falconUserRoles = new HashSet<FalconUserRole>(0);
     private Set<FalconStaff> falconStaffs = new HashSet<FalconStaff>(0);
     private Set<FalconLocation> falconLocations = new HashSet<FalconLocation>(0);

    public FalconUser() {
    }

	
    public FalconUser(String username, String password, String name) {
        this.username = username;
        this.password = password;
        this.name = name;
    }
    public FalconUser(String username, String password, String name, String email, String phone, Set<FalconPatron> falconPatronsForPatron, Set<FalconPatron> falconPatronsForAdmin, Set<FalconAppointmentPatron> falconAppointmentPatrons, Set<FalconUserRole> falconUserRoles, Set<FalconStaff> falconStaffs, Set<FalconLocation> falconLocations) {
       this.username = username;
       this.password = password;
       this.name = name;
       this.email = email;
       this.phone = phone;
       this.falconPatronsForPatron = falconPatronsForPatron;
       this.falconPatronsForAdmin = falconPatronsForAdmin;
       this.falconAppointmentPatrons = falconAppointmentPatrons;
       this.falconUserRoles = falconUserRoles;
       this.falconStaffs = falconStaffs;
       this.falconLocations = falconLocations;
    }
   
     @Id 

    
    @Column(name="username", unique=true, nullable=false, length=100)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=64)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="name", nullable=false, length=200)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="phone", length=25)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="falconUserByPatron")
    public Set<FalconPatron> getFalconPatronsForPatron() {
        return this.falconPatronsForPatron;
    }
    
    public void setFalconPatronsForPatron(Set<FalconPatron> falconPatronsForPatron) {
        this.falconPatronsForPatron = falconPatronsForPatron;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="falconUserByAdmin")
    public Set<FalconPatron> getFalconPatronsForAdmin() {
        return this.falconPatronsForAdmin;
    }
    
    public void setFalconPatronsForAdmin(Set<FalconPatron> falconPatronsForAdmin) {
        this.falconPatronsForAdmin = falconPatronsForAdmin;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="falconUser")
    public Set<FalconAppointmentPatron> getFalconAppointmentPatrons() {
        return this.falconAppointmentPatrons;
    }
    
    public void setFalconAppointmentPatrons(Set<FalconAppointmentPatron> falconAppointmentPatrons) {
        this.falconAppointmentPatrons = falconAppointmentPatrons;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="falconUser")
    public Set<FalconUserRole> getFalconUserRoles() {
        return this.falconUserRoles;
    }
    
    public void setFalconUserRoles(Set<FalconUserRole> falconUserRoles) {
        this.falconUserRoles = falconUserRoles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="falconUser")
    public Set<FalconStaff> getFalconStaffs() {
        return this.falconStaffs;
    }
    
    public void setFalconStaffs(Set<FalconStaff> falconStaffs) {
        this.falconStaffs = falconStaffs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="falconUser")
    public Set<FalconLocation> getFalconLocations() {
        return this.falconLocations;
    }
    
    public void setFalconLocations(Set<FalconLocation> falconLocations) {
        this.falconLocations = falconLocations;
    }




}


