package com.twistlet.falcon.model.entity;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FalconAppointmentPatron generated by hbm2java
 */
@Entity
@Table(name="falcon_appointment_patron"
)
public class FalconAppointmentPatron  implements java.io.Serializable {


     private Integer id;
     private FalconAppointment falconAppointment;
     private FalconPatron falconPatron;

    public FalconAppointmentPatron() {
    }

    public FalconAppointmentPatron(FalconAppointment falconAppointment, FalconPatron falconPatron) {
       this.falconAppointment = falconAppointment;
       this.falconPatron = falconPatron;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="appointment", nullable=false)
    public FalconAppointment getFalconAppointment() {
        return this.falconAppointment;
    }
    
    public void setFalconAppointment(FalconAppointment falconAppointment) {
        this.falconAppointment = falconAppointment;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="patron", nullable=false)
    public FalconPatron getFalconPatron() {
        return this.falconPatron;
    }
    
    public void setFalconPatron(FalconPatron falconPatron) {
        this.falconPatron = falconPatron;
    }




}


