package com.twistlet.falcon.model.entity;


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FalconMessageLog generated by hbm2java
 */
@Entity
@Table(name="falcon_message_log"
)
public class FalconMessageLog  implements java.io.Serializable {


     private Integer id;
     private String destination;
     private String messageType;
     private String message;
     private Date sentTime;
     private String errorMessage;

    public FalconMessageLog() {
    }

	
    public FalconMessageLog(String destination, String messageType, String message, Date sentTime) {
        this.destination = destination;
        this.messageType = messageType;
        this.message = message;
        this.sentTime = sentTime;
    }
    public FalconMessageLog(String destination, String messageType, String message, Date sentTime, String errorMessage) {
       this.destination = destination;
       this.messageType = messageType;
       this.message = message;
       this.sentTime = sentTime;
       this.errorMessage = errorMessage;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="destination", nullable=false, length=100)
    public String getDestination() {
        return this.destination;
    }
    
    public void setDestination(String destination) {
        this.destination = destination;
    }

    
    @Column(name="message_type", nullable=false, length=10)
    public String getMessageType() {
        return this.messageType;
    }
    
    public void setMessageType(String messageType) {
        this.messageType = messageType;
    }

    
    @Column(name="message", nullable=false, length=1024)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="sent_time", nullable=false, length=19)
    public Date getSentTime() {
        return this.sentTime;
    }
    
    public void setSentTime(Date sentTime) {
        this.sentTime = sentTime;
    }

    
    @Column(name="error_message", length=1024)
    public String getErrorMessage() {
        return this.errorMessage;
    }
    
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }




}


