package com.twistlet.falcon.model.entity;


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FalconStaff generated by hbm2java
 */
@Entity
@Table(name="falcon_staff"
)
public class FalconStaff  implements java.io.Serializable {


     private Integer id;
     private FalconUser falconUser;
     private String name;
     private String nric;
     private Set<FalconAppointment> falconAppointments = new HashSet<FalconAppointment>(0);

    public FalconStaff() {
    }

	
    public FalconStaff(FalconUser falconUser, String name, String nric) {
        this.falconUser = falconUser;
        this.name = name;
        this.nric = nric;
    }
    public FalconStaff(FalconUser falconUser, String name, String nric, Set<FalconAppointment> falconAppointments) {
       this.falconUser = falconUser;
       this.name = name;
       this.nric = nric;
       this.falconAppointments = falconAppointments;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="admin", nullable=false)
    public FalconUser getFalconUser() {
        return this.falconUser;
    }
    
    public void setFalconUser(FalconUser falconUser) {
        this.falconUser = falconUser;
    }

    
    @Column(name="name", nullable=false, length=200)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="nric", nullable=false, length=20)
    public String getNric() {
        return this.nric;
    }
    
    public void setNric(String nric) {
        this.nric = nric;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="falconStaff")
    public Set<FalconAppointment> getFalconAppointments() {
        return this.falconAppointments;
    }
    
    public void setFalconAppointments(Set<FalconAppointment> falconAppointments) {
        this.falconAppointments = falconAppointments;
    }




}


