package com.twistlet.falcon.model.entity;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FalconUserRole generated by hbm2java
 */
@Entity
@Table(name="falcon_user_role"
)
public class FalconUserRole  implements java.io.Serializable {


     private Integer id;
     private FalconUser falconUser;
     private FalconRole falconRole;

    public FalconUserRole() {
    }

    public FalconUserRole(FalconUser falconUser, FalconRole falconRole) {
       this.falconUser = falconUser;
       this.falconRole = falconRole;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="username", nullable=false)
    public FalconUser getFalconUser() {
        return this.falconUser;
    }
    
    public void setFalconUser(FalconUser falconUser) {
        this.falconUser = falconUser;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="rolename", nullable=false)
    public FalconRole getFalconRole() {
        return this.falconRole;
    }
    
    public void setFalconRole(FalconRole falconRole) {
        this.falconRole = falconRole;
    }




}


