package com.twistlet.falcon.model.entity;


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FalconLocation generated by hbm2java
 */
@Entity
@Table(name="falcon_location"
)
public class FalconLocation  implements java.io.Serializable {


     private Integer id;
     private FalconUser falconUser;
     private String name;
     private Boolean valid;
     private Set<FalconAppointment> falconAppointments = new HashSet<FalconAppointment>(0);

    public FalconLocation() {
    }

	
    public FalconLocation(FalconUser falconUser) {
        this.falconUser = falconUser;
    }
    public FalconLocation(FalconUser falconUser, String name, Boolean valid, Set<FalconAppointment> falconAppointments) {
       this.falconUser = falconUser;
       this.name = name;
       this.valid = valid;
       this.falconAppointments = falconAppointments;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="admin", nullable=false)
    public FalconUser getFalconUser() {
        return this.falconUser;
    }
    
    public void setFalconUser(FalconUser falconUser) {
        this.falconUser = falconUser;
    }

    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="valid")
    public Boolean getValid() {
        return this.valid;
    }
    
    public void setValid(Boolean valid) {
        this.valid = valid;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="falconLocation")
    public Set<FalconAppointment> getFalconAppointments() {
        return this.falconAppointments;
    }
    
    public void setFalconAppointments(Set<FalconAppointment> falconAppointments) {
        this.falconAppointments = falconAppointments;
    }




}


