package com.twistlet.falcon.model.entity;


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FalconRole generated by hbm2java
 */
@Entity
@Table(name="falcon_role"
)
public class FalconRole  implements java.io.Serializable {


     private String roleName;
     private Set<FalconUserRole> falconUserRoles = new HashSet<FalconUserRole>(0);

    public FalconRole() {
    }

	
    public FalconRole(String roleName) {
        this.roleName = roleName;
    }
    public FalconRole(String roleName, Set<FalconUserRole> falconUserRoles) {
       this.roleName = roleName;
       this.falconUserRoles = falconUserRoles;
    }
   
     @Id 

    
    @Column(name="role_name", unique=true, nullable=false, length=50)
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="falconRole")
    public Set<FalconUserRole> getFalconUserRoles() {
        return this.falconUserRoles;
    }
    
    public void setFalconUserRoles(Set<FalconUserRole> falconUserRoles) {
        this.falconUserRoles = falconUserRoles;
    }




}


