package com.twistlet.falcon.model.entity;


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FalconPasswordChange generated by hbm2java
 */
@Entity
@Table(name="falcon_password_change"
)
public class FalconPasswordChange  implements java.io.Serializable {


     private Integer id;
     private String nric;
     private String randomString;
     private Boolean executed;
     private Date dateRequest;

    public FalconPasswordChange() {
    }

    public FalconPasswordChange(String nric, String randomString, Boolean executed, Date dateRequest) {
       this.nric = nric;
       this.randomString = randomString;
       this.executed = executed;
       this.dateRequest = dateRequest;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nric", length=50)
    public String getNric() {
        return this.nric;
    }
    
    public void setNric(String nric) {
        this.nric = nric;
    }

    
    @Column(name="random_string", length=50)
    public String getRandomString() {
        return this.randomString;
    }
    
    public void setRandomString(String randomString) {
        this.randomString = randomString;
    }

    
    @Column(name="executed")
    public Boolean getExecuted() {
        return this.executed;
    }
    
    public void setExecuted(Boolean executed) {
        this.executed = executed;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_request", length=10)
    public Date getDateRequest() {
        return this.dateRequest;
    }
    
    public void setDateRequest(Date dateRequest) {
        this.dateRequest = dateRequest;
    }




}


