package com.twistlet.falcon.model.entity;


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FalconUser generated by hbm2java
 */
@Entity
@Table(name="falcon_user"
)
public class FalconUser  implements java.io.Serializable {


     private String username;
     private String password;
     private String name;
     private Set<FalconUserRole> falconUserRoles = new HashSet<FalconUserRole>(0);

    public FalconUser() {
    }

	
    public FalconUser(String username) {
        this.username = username;
    }
    public FalconUser(String username, String password, String name, Set<FalconUserRole> falconUserRoles) {
       this.username = username;
       this.password = password;
       this.name = name;
       this.falconUserRoles = falconUserRoles;
    }
   
     @Id 

    
    @Column(name="username", unique=true, nullable=false, length=100)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", length=64)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="name", length=200)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="falconUser")
    public Set<FalconUserRole> getFalconUserRoles() {
        return this.falconUserRoles;
    }
    
    public void setFalconUserRoles(Set<FalconUserRole> falconUserRoles) {
        this.falconUserRoles = falconUserRoles;
    }




}


